"""Resize scout_embeddings.embedding from vector(1024) to vector(768).

Switched embedding backend from Voyage AI (voyage-3-lite, 1024-dim) to
Ollama nomic-embed-text (768-dim). All existing embedding rows are cleared
because they were generated by a different model and would give incorrect
similarity scores against new 768-dim query vectors.

After running this migration, rebuild the index:
    POST /api/agent/index

Revision ID: 015
Revises: 014
Create Date: 2026-04-13
"""
from alembic import op

revision = "015"
down_revision = "014"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop the IVFFlat index first — it's dimension-specific.
    op.execute("DROP INDEX IF EXISTS ix_scout_embeddings_ivfflat")

    # Clear existing rows: they were embedded with voyage-3-lite (1024-dim)
    # and are incompatible with nomic-embed-text (768-dim) query vectors.
    op.execute("TRUNCATE TABLE scout_embeddings")

    # Resize the column to 768 dimensions.
    op.execute("""
        ALTER TABLE scout_embeddings
        ALTER COLUMN embedding TYPE vector(768)
        USING embedding::vector(768)
    """)

    # Recreate the IVFFlat index for the new dimension.
    op.execute("""
        CREATE INDEX ix_scout_embeddings_ivfflat
        ON scout_embeddings
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 50)
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_scout_embeddings_ivfflat")
    op.execute("TRUNCATE TABLE scout_embeddings")
    op.execute("""
        ALTER TABLE scout_embeddings
        ALTER COLUMN embedding TYPE vector(1024)
        USING embedding::vector(1024)
    """)
    op.execute("""
        CREATE INDEX ix_scout_embeddings_ivfflat
        ON scout_embeddings
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 50)
    """)
